# -*- coding: utf-8 -*-
"""genai_project_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FF9dYtky34DouVyB6395w4Vtr7FRnHIj

#convertion to text form pdf, text book page , picture  wtih detailed explanation of image
"""

!pip install pymupdf
!pip install pytesseract # Install pytesseract
!sudo apt install tesseract-ocr
!pip install pytesseract
!pip install transformers
import requests
import io
from PIL import Image
import pytesseract
from transformers import BlipProcessor, BlipForConditionalGeneration, pipeline
import fitz  # PyMuPDF for PDF processing
import os  # For checking file existence
from requests.exceptions import HTTPError
# Initialize Tesseract for OCR
pytesseract.pytesseract.tesseract_cmd = r'/usr/bin/tesseract'  # Adjust the path to your Tesseract executable

# Initialize the image captioning model and processor (BLIP)
feature_extractor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")
tokenizer = feature_extractor.tokenizer

# Initialize a GPT-based text generation pipeline (e.g., from Hugging Face Transformers)
gpt_pipeline = pipeline("text-generation", model="gpt2")

def enhance_text_with_gpt(input_text):
    """Enhances the extracted text using GPT for a detailed explanation.

    Args:
        input_text: The text extracted from an image or PDF.

    Returns:
        A detailed explanation generated by GPT.
    """
    prompt = f"Provide a detailed explanation or context for the following text: \"{input_text}\""
    # Use max_new_tokens to control the length of generated text
    enhanced_text = gpt_pipeline(prompt, max_new_tokens=100, num_return_sequences=1)[0]['generated_text']
    return enhanced_text

def extract_text_and_images_from_pdf(pdf_source):
    """Extracts text and images from a PDF using PyMuPDF and provides detailed descriptions for images.

    Args:
        pdf_source: URL or local path of the PDF file.

    Returns:
        A dictionary containing extracted text and detailed descriptions of images.
    """
    try:
        # Attempt to fetch the PDF from the URL
        response = requests.get(pdf_source)
        response.raise_for_status()  # Raise HTTPError for bad responses
        pdf_document = fitz.open(io.BytesIO(response.content))
    except (requests.exceptions.RequestException, HTTPError):
        # If URL access fails, assume it's a local file path
        # Check if the file exists and open it directly with fitz
        if os.path.isfile(pdf_source):
            pdf_document = fitz.open(pdf_source)
        else:
            raise FileNotFoundError(f"Could not access PDF at: {pdf_source}")

    result = {"text": "", "image_descriptions": []}

    # Extract text and images from all pages
    for page_num in range(pdf_document.page_count):
        page = pdf_document.load_page(page_num)
        extracted_text = page.get_text()
        result["text"] += extracted_text

        # Enhance text with GPT for detailed explanations
        if extracted_text.strip():
            detailed_text = enhance_text_with_gpt(extracted_text)
            result["text"] += f"\n\nEnhanced Explanation:\n{detailed_text}\n"

        # Extract images from the page
        images = page.get_images(full=True)
        for img_index, img in enumerate(images):
            xref = img[0]
            base_image = pdf_document.extract_image(xref)
            image_bytes = base_image["image"]
            image = Image.open(io.BytesIO(image_bytes))

            # Generate a detailed description for the image
            pixel_values = feature_extractor(images=image, return_tensors="pt").pixel_values
            generated_ids = model.generate(pixel_values, max_length=50, num_beams=4)
            description = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

            result["image_descriptions"].append({
                "page": page_num + 1,
                "description": description
            })

    return result

def generate_text_from_image(image_url):
    """Converts an image to text

    Args:
        image_url: URL of the image file.

    Returns:
        A text output describing or extracting text from the image.
    """
    # Fetch the image from the URL
    response = requests.get(image_url, stream=True)
    response.raise_for_status()
    image = Image.open(io.BytesIO(response.content))

    # First, try extracting text using OCR (for images with textual content like textbook pages)
    extracted_text = pytesseract.image_to_string(image)

    # If OCR returns meaningful text, enhance it with GPT
    if extracted_text.strip():
        detailed_text = enhance_text_with_gpt(extracted_text)
        return f"Extracted Text:\n{extracted_text}\n\nEnhanced Explanation:\n{detailed_text}"

    # If no meaningful text, use image captioning model to describe the image (for images like pictures)
    # Prepare the image for the model
    pixel_values = feature_extractor(images=image, return_tensors="pt").pixel_values

    # Generate the caption with more details
    generated_ids = model.generate(pixel_values, max_length=50, num_beams=4)
    generated_text = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

    return generated_text

def process_input(input_source):
    """Determines whether the input is a PDF or an image URL and processes accordingly.

    Args:
        input_source: URL or local path of the PDF or image.

    Returns:
        Extracted text or generated description.
    """
    if input_source.lower().endswith(('.pdf')):
        # Process as PDF
        return extract_text_and_images_from_pdf(input_source)
    else:
        # Process as Image
        return generate_text_from_image(input_source)

# Example usage:
input_source = input("Enter URL or local path of the PDF or image (textbook page or picture): ")

# Process the input
output = process_input(input_source)

if isinstance(output, dict):
    print("\nExtracted Text from PDF:")
    print(output["text"])
    print("\nImage Descriptions:")
    for img_desc in output["image_descriptions"]:
        print(f"Page {img_desc['page']}: {img_desc['description']}")
else:
    print("\nOutput:")
    print(output)

"""#text ot audio converstion"""

!pip install gTTS # Install gTTS module

from gtts import gTTS
from io import BytesIO
from IPython.display import Audio

def text_to_speech(text, lang='en'):
  """Generates audio from text using gTTS.

  Args:
    text: The text to be converted to audio.
    lang: The language code for the audio.

  Returns:
    An Audio object that can be played directly in the notebook.
  """

  tts = gTTS(text=text, lang=lang)
  audio_bytes = BytesIO()
  tts.write_to_fp(audio_bytes)
  audio_bytes.seek(0)
  # Instead of passing audio_bytes directly, we use it to get raw data
  # and set the rate to a default value. You might need to adjust the rate
  # based on your audio's actual sampling rate.
  return Audio(audio_bytes.read(), rate=22050) # Assuming a default rate of 22050 Hz

# Example usage:
text = output
audio = text_to_speech(text)
display(audio)

"""#accuracy scores

"""

!pip install python-Levenshtein # Install the Levenshtein library

# prompt: above is the code that generates text form image and audio form text generated from image . give accuracy  metrics of  the code output . take input and output form above code .and give only accuracy code

from sklearn.metrics import accuracy_score
import Levenshtein

def calculate_accuracy(ground_truth, generated_text):
    """
    Calculates accuracy metrics for generated text compared to ground truth.

    Args:
        ground_truth: The correct or expected text.
        generated_text: The text generated by the model.

    Returns:
        A dictionary containing accuracy metrics.
    """
    metrics = {}

    # Levenshtein Distance (Edit Distance)
    metrics["levenshtein_distance"] = Levenshtein.distance(ground_truth.lower(), generated_text.lower())
    metrics["levenshtein_ratio"] = Levenshtein.ratio(ground_truth.lower(), generated_text.lower())


    # Character-level accuracy (ignoring case and whitespace)
    ground_truth_processed = "".join(ground_truth.lower().split())
    generated_text_processed = "".join(generated_text.lower().split())

    if len(ground_truth_processed)>0:
      metrics["char_accuracy"] = sum(1 for a, b in zip(ground_truth_processed, generated_text_processed) if a == b) / len(ground_truth_processed)
    else:
      metrics["char_accuracy"] = 0 # Handle cases where ground truth is empty.

    # Word-level accuracy (case-insensitive)
    ground_truth_words = set(ground_truth.lower().split())
    generated_text_words = set(generated_text.lower().split())

    if len(ground_truth_words) > 0:
        metrics["word_accuracy"] = len(ground_truth_words.intersection(generated_text_words)) / len(ground_truth_words)
    else:
        metrics["word_accuracy"] = 0

    return metrics

# Example usage (replace with your actual ground truth and generated text):
ground_truth_text = "This is a sample ground truth text."
# Assuming 'output' is from your original code
generated_output = output if isinstance(output, str) else str(output) # Handle dict or str output

accuracy_results = calculate_accuracy(ground_truth_text, generated_output)
accuracy_results

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import Levenshtein

def calculate_accuracy(ground_truth, generated_text):
    """
    Calculates accuracy metrics for generated text compared to ground truth.

    Args:
        ground_truth: The correct or expected text.
        generated_text: The text generated by the model.

    Returns:
        A dictionary containing accuracy metrics.
    """
    metrics = {}

    # Levenshtein Distance and Ratio (as before)
    metrics["levenshtein_distance"] = Levenshtein.distance(ground_truth.lower(), generated_text.lower())
    metrics["levenshtein_ratio"] = Levenshtein.ratio(ground_truth.lower(), generated_text.lower())

    # Character-level accuracy (as before)
    ground_truth_processed = "".join(ground_truth.lower().split())
    generated_text_processed = "".join(generated_text.lower().split())
    if len(ground_truth_processed) > 0:
        metrics["char_accuracy"] = sum(1 for a, b in zip(ground_truth_processed, generated_text_processed) if a == b) / len(ground_truth_processed)
    else:
        metrics["char_accuracy"] = 0

    # Word-level accuracy (as before)
    ground_truth_words = set(ground_truth.lower().split())
    generated_text_words = set(generated_text.lower().split())
    if len(ground_truth_words) > 0:
        metrics["word_accuracy"] = len(ground_truth_words.intersection(generated_text_words)) / len(ground_truth_words)
    else:
        metrics["word_accuracy"] = 0

    # --- New Metrics ---
    # Precision, Recall, and F1-score (treating words as tokens)
    ground_truth_tokens = ground_truth.lower().split()
    generated_tokens = generated_text.lower().split()

    # Pad the shorter list to have the same length for calculation
    max_len = max(len(ground_truth_tokens), len(generated_tokens))
    ground_truth_tokens += [''] * (max_len - len(ground_truth_tokens))
    generated_tokens += [''] * (max_len - len(generated_tokens))

    metrics["precision"] = precision_score(ground_truth_tokens, generated_tokens, average='weighted', zero_division=0)
    metrics["recall"] = recall_score(ground_truth_tokens, generated_tokens, average='weighted', zero_division=0)
    metrics["f1_score"] = f1_score(ground_truth_tokens, generated_tokens, average='weighted', zero_division=0)


    # --- End of New Metrics ---

    return metrics

# ... (rest of the code remains the same) ...

# Example usage (replace with your actual ground truth and generated text):
ground_truth_text = "This is a sample ground truth text."
# Assuming 'output' is from your original code
generated_output = output if isinstance(output, str) else str(output) # Handle dict or str output

# Use ground_truth_text instead of ground_truth:
ground_truth_tokens = ground_truth_text.lower().split()  # Changed here
generated_tokens = generated_output.lower().split()  # Use generated_output for consistency
# Pad the shorter list to have the same length for calculation
max_len = max(len(ground_truth_tokens), len(generated_tokens))
ground_truth_tokens += [''] * (max_len - len(ground_truth_tokens))
generated_tokens += [''] * (max_len - len(generated_tokens))
# Assuming 'metrics' is defined somewhere before this
metrics = {}  # If 'metrics' wasn't previously defined, define it here
metrics["precision"] = precision_score(ground_truth_tokens, generated_tokens, average='weighted', zero_division=0)
metrics["recall"] = recall_score(ground_truth_tokens, generated_tokens, average='weighted', zero_division=0)
metrics["f1_score"] = f1_score(ground_truth_tokens, generated_tokens, average='weighted', zero_division=0)

# Calculate and print accuracy results
accuracy_results = calculate_accuracy(ground_truth_text, generated_output)
print(accuracy_results)  # Print the accuracy results

# prompt: can you plot graphs for the accuracy values , give all in one , give point  of each  data on plots

import matplotlib.pyplot as plt

def plot_accuracy_metrics(accuracy_results):
    """Plots accuracy metrics from a dictionary.

    Args:
        accuracy_results: A dictionary containing accuracy metrics.
    """

    metrics_to_plot = ["levenshtein_distance", "levenshtein_ratio", "char_accuracy",
                       "word_accuracy", "precision", "recall", "f1_score"]

    # Extract metric names and values
    metric_names = []
    metric_values = []
    for metric in metrics_to_plot:
        if metric in accuracy_results:  # Check if the metric exists
            metric_names.append(metric)
            metric_values.append(accuracy_results[metric])


    # Create the plot
    plt.figure(figsize=(10, 6))  # Adjust figure size as needed
    plt.plot(metric_names, metric_values, marker='o', linestyle='-')
    plt.xlabel("Metrics")
    plt.ylabel("Values")
    plt.title("Accuracy Metrics")

    # Annotate each point with its value
    for i, value in enumerate(metric_values):
        plt.annotate(f"{value:.4f}", (metric_names[i], value), textcoords="offset points", xytext=(0,10), ha='center')

    plt.grid(True)
    plt.xticks(rotation=45, ha='right') # Rotate x-axis labels for better readability
    plt.tight_layout() # Adjust layout to prevent labels from overlapping
    plt.show()


# Example usage (assuming accuracy_results is already calculated):
plot_accuracy_metrics(accuracy_results)

# prompt: adjust this code to pie graph , give only pie chart

import matplotlib.pyplot as plt

def plot_accuracy_metrics_pie(accuracy_results):
    """Plots accuracy metrics from a dictionary as a pie chart.

    Args:
        accuracy_results: A dictionary containing accuracy metrics.
    """

    metrics_to_plot = ["levenshtein_ratio", "char_accuracy", "word_accuracy", "precision", "recall", "f1_score"]

    # Filter out metrics not present in the results
    filtered_metrics = {metric: accuracy_results[metric] for metric in metrics_to_plot if metric in accuracy_results}

    # Create the pie chart
    plt.figure(figsize=(8, 8))
    plt.pie(filtered_metrics.values(), labels=filtered_metrics.keys(), autopct='%1.1f%%', startangle=90)
    plt.title("Accuracy Metrics")
    plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
    plt.show()

# Example usage (assuming accuracy_results is already calculated):
plot_accuracy_metrics_pie(accuracy_results)

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd  # Import pandas with the alias 'pd'


def plot_accuracy_metrics_violin(accuracy_results):
    """Plots accuracy metrics from a dictionary as a violin plot.

    Args:
        accuracy_results: A dictionary containing accuracy metrics.
    """

    metrics_to_plot = ["levenshtein_ratio", "char_accuracy", "word_accuracy", "precision", "recall", "f1_score"]

    # Filter out metrics not present in the results
    filtered_metrics = {metric: accuracy_results[metric] for metric in metrics_to_plot if metric in accuracy_results}

    # Convert the dictionary to a suitable format for seaborn's violinplot
    metric_data = []
    for metric, value in filtered_metrics.items():
        metric_data.append({"Metric": metric, "Value": value})

    metric_df = pd.DataFrame(metric_data)  # Now pd is defined

    # Create the violin plot
    plt.figure(figsize=(10, 6))
    sns.violinplot(x="Metric", y="Value", data=metric_df)
    plt.title("Accuracy Metrics (Violin Plot)")
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()


# Example usage (assuming accuracy_results is already calculated):
plot_accuracy_metrics_violin(accuracy_results)

# prompt: can you plot graphs for the BLEU Accuracy	0.04
# Sequence Match Accuracy	 0.29
#  values

import matplotlib.pyplot as plt

def plot_accuracy_values(bleu, sequence_match):
    """Plots BLEU and Sequence Match accuracy values."""

    metrics = ['BLEU Accuracy', 'Sequence Match Accuracy']
    values = [bleu, sequence_match]

    plt.figure(figsize=(8, 6))
    plt.bar(metrics, values, color=['skyblue', 'lightcoral'])
    plt.ylabel('Accuracy')
    plt.title('Accuracy Metrics')

    # Add value labels on top of the bars
    for i, v in enumerate(values):
        plt.text(i, v, str(round(v, 2)), ha='center', va='bottom')

    plt.show()

# Example usage:
plot_accuracy_values(0.04, 0.29)

